# Site settings
title: FooBar
email: davide.parisi@gmx.com
description: A Foo blog. Well, not so foo.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: fading_blues
github_username:  fadingblues

# Build settings
markdown: kramdown

exclude: [
	".bowerrc",
	"bower.json",
	"package.json",
	"Gruntfile.coffee",
	"node_modules"
]
